#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sirafe <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/21 16:46:00 by sirafe            #+#    #+#              #
#    Updated: 2018/11/21 16:46:02 by sirafe           ###   ########.fr        #
#                                                                              #
#******************************************************************************#


NAME = ft_display_file
C = ft_display_file.c

all:
				gcc $(C) -o $(NAME)

clean:
				/bin/rm -f *.o

fclean:			clean
				/bin/rm -f $(NAME)

re: fclean re